# Generated by Django 6.0.4 on 2026-05-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('iso_two_code', models.CharField(max_length=2)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taken_on', models.DateTimeField()),
                ('source', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_number', models.IntegerField()),
                ('in_book_reference', models.TextField()),
                ('text', models.TextField()),
                ('grade', models.TextField()),
                ('link', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.collection')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.language')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.snapshot')),
            ],
        ),
    ]
